name: 'Emergence: Deploy Site Preview'
description: 'Deploys a preview site from a branch'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  environment-name:
    description: 'Name for environment to deploy preview to'
    required: false
    default: ''
  environment-transient:
    description: 'Whether named environment is transient'
    required: false
    default: ''
outputs:
  environment-name:
    description: 'Name of environment deployed to'
    value: ${{ steps.determine-environment.outputs.environment-name }}
  environment-transient:
    description: 'Whether deployed environment was marked transient'
    value: ${{ steps.determine-environment.outputs.environment-transient }}

runs:
  using: composite
  steps:

  - name: Determine environment to deploy to
    id: determine-environment
    shell: bash
    env:
      ENVIRONMENT_NAME: ${{ inputs.environment-name }}
      ENVIRONMENT_TRANSIENT: ${{ inputs.environment-transient }}
    run: |
      if [ -z "${ENVIRONMENT_NAME}" ]; then
        echo "Attempting to determine environment name automatically"

        if [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
          ENVIRONMENT_NAME="pr-$(jq --raw-output .pull_request.number "${GITHUB_EVENT_PATH}")"
          ENVIRONMENT_TRANSIENT_DEFAULT='true'
        # else
        #   ENVIRONMENT_NAME="latest"
        #   ENVIRONMENT_TRANSIENT_DEFAULT='false'
        else
          echo "Could not detect environment name. Either specify environment-name input or only trigger from pull request event"
          exit 1
        fi
      fi

      if [ -z "${ENVIRONMENT_TRANSIENT}" ]; then
        if [ -n "${ENVIRONMENT_TRANSIENT_DEFAULT}" ]; then
          ENVIRONMENT_TRANSIENT="${ENVIRONMENT_TRANSIENT_DEFAULT}"
        else
          ENVIRONMENT_TRANSIENT='true'
        fi
      fi

      echo "Outputting: environment-name=${ENVIRONMENT_NAME}"
      echo "environment-name=${ENVIRONMENT_NAME}" >> "${GITHUB_OUTPUT}"

      echo "Outputting: environment-transient=${ENVIRONMENT_TRANSIENT}"
      echo "environment-transient=${ENVIRONMENT_TRANSIENT}" >> "${GITHUB_OUTPUT}"
