default_timezone = "America/New_York"

[core]
root = ""
debug = false
production = true

[nginx]
# root = "web/public"
# index = "index.php"
server_snippet = "# php-runtime nginx snippet"

[sites.default]
database = "emergence-site"
primary_hostname = "localhost"
