#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

ln -vsfT "{{pkg.svc_data_path}}" "{{pkg.svc_var_path}}/site-data"

mkdir -vp \
    "{{pkg.svc_var_path}}/logs" \
    "{{pkg.svc_var_path}}/site"

chown -R hab:hab \
    "{{pkg.svc_var_path}}/logs" \
    "{{pkg.svc_var_path}}/site" \
    "{{pkg.svc_data_path}}" \
    || true
