#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

mkdir -p \
    "{{pkg.svc_var_path}}/logs" \
    "{{pkg.svc_var_path}}/site" \
    "{{pkg.svc_var_path}}/site-data"

chown -R hab:hab \
    "{{pkg.svc_var_path}}/logs" \
    "{{pkg.svc_var_path}}/site" \
    "{{pkg.svc_var_path}}/site-data"
