name: Publish actions to develop stream

on:
  push:
    branches: [develop]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HAB_LICENSE: accept-no-persist

jobs:
  actions-publish-develop:
    runs-on: ubuntu-latest
    steps:

    - name: 'Update holobranch: github-actions/build-site-container/develop'
      uses: JarvusInnovations/hologit@actions/projector/v1
      with:
        ref: develop
        holobranch: github-actions/build-site-container
        commit-to: github-actions/build-site-container/develop

    - name: 'Update holobranch: github-actions/deploy-site-preview/develop'
      uses: JarvusInnovations/hologit@actions/projector/v1
      with:
        ref: develop
        holobranch: github-actions/deploy-site-preview
        commit-to: github-actions/deploy-site-preview/develop

    - name: 'Update holobranch: github-actions/destroy-site-preview/develop'
      uses: JarvusInnovations/hologit@actions/projector/v1
      with:
        ref: develop
        holobranch: github-actions/destroy-site-preview
        commit-to: github-actions/destroy-site-preview/develop
