name: 'Habitat: Publish and Promote Package'

on:
  push:
    tags: [ 'v*' ]

env:
  HAB_LICENSE: accept-no-persist

jobs:
  habitat-publish:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setting pkg_version version
      run: |
        # extract version from tag name without 'v' prefix
        pkg_version="${GITHUB_REF:11}"

        # trim patch version to only set MAJOR.MINOR in Habitat
        pkg_version="${pkg_version%.*}"

        # write into plan.sh
        sed -i "/^pkg_version=.*/c\pkg_version='${pkg_version}'" plan.sh

    - uses: JarvusInnovations/infra-components@channels/github-actions/habitat-publish/latest
      with:
        checkout: false
        hab-origin-key-secret: ${{ secrets.HAB_ORIGIN_KEY }}
        hab-origin-key-public: ${{ secrets.HAB_ORIGIN_KEY_PUB }}
        hab-auth-token: ${{ secrets.HAB_AUTH_TOKEN }}

    - name: Build scaffolding-site
      run: hab pkg exec core/hab-plan-build hab-plan-build ./scaffolding-site

    - name: Upload scaffolding-site
      shell: bash
      env:
        HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
      run: |
        source results/last_build.env
        hab pkg upload "results/${pkg_artifact}" -c stable

    - name: Build scaffolding-composite
      run: hab pkg exec core/hab-plan-build hab-plan-build ./scaffolding-composite

    - name: Upload scaffolding-composite
      shell: bash
      env:
        HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
      run: |
        source results/last_build.env
        hab pkg upload "results/${pkg_artifact}" -c stable

    - name: Build Docker container image with runtime dependencies
      run: |
        docker build . \
          --build-arg=HAB_LICENSE=accept-no-persist \
          --target=runtime-deps \
          --tag="ghcr.io/${GITHUB_REPOSITORY,,}:runtime-deps"

    - name: Build Docker container image with build dependencies
      run: |
        docker build . \
          --build-arg=HAB_LICENSE=accept-no-persist \
          --cache-from="ghcr.io/${GITHUB_REPOSITORY,,}:runtime-deps" \
          --target=build-deps \
          --tag="ghcr.io/${GITHUB_REPOSITORY,,}:build-deps"

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push runtime and build Docker container images
      run: |
        docker push "ghcr.io/${GITHUB_REPOSITORY,,}:runtime-deps"
        docker push "ghcr.io/${GITHUB_REPOSITORY,,}:build-deps"
